# Generated by Django 2.0.1 on 2018-02-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('priority', models.CharField(choices=[('h', 'High Priority'), ('m', 'Medium Priority'), ('l', 'Low Priority')], max_length=1, null=True)),
            ],
        ),
    ]
